# Generated by Django 5.2.6 on 2025-10-12 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Prospectors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('copy', models.FileField(upload_to='store/prospectors/')),
                ('logo', models.ImageField(upload_to='store/prospectors/')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='question_papers/')),
                ('complexity_rating', models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')])),
                ('number_of_questions', models.TextField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questpaper.department')),
                ('educator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.educator')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.grade')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.school')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.term')),
                ('topics', models.ManyToManyField(related_name='question_papers', to='questpaper.topic')),
            ],
        ),
    ]
