# Generated by Django 5.2.6 on 2025-10-12 22:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('details', models.TextField(blank=True, max_length=2000, null=True)),
                ('disability', models.TextField(blank=True, max_length=2000, null=True)),
                ('student', models.CharField(blank=True, max_length=2000, null=True)),
                ('address', models.CharField(blank=True, max_length=2000, null=True)),
                ('bursary', models.CharField(blank=True, max_length=2000, null=True)),
                ('varsity', models.TextField(blank=True, max_length=2000, null=True)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('keen', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universitys',
            },
        ),
    ]
