# Generated by Django 5.2.6 on 2025-10-14 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_circuit_alter_prospectors_options_alter_school_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='prospectors',
            table='main_app_prospectors',
        ),
    ]
