# Generated by Django 5.2.6 on 2025-10-16 09:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
